[package]
name = "sara_engine"
version = "0.2.3"
edition = "2021"

[lib]
name = "sara_rust_core"
path = "src/sara_engine/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.3", features = ["extension-module"] }
rayon = "1.10.0"